      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_IP }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            echo "Starting deployment on EC2..."
            cd /var/www/html
            sudo rm -f index.html
            sudo wget -O index.html https://raw.githubusercontent.com/${{ github.repository }}/main/index1.html
            sudo systemctl restart apache2
            echo "Deployment complete!"
